wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1665748731
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 13
      - 16
      4: 3.7.11
      5: 0.12.9
      8:
      - 5
      9:
        2: CycleGAN-and-pix2pix
batch_size:
  desc: null
  value: 4
beta1:
  desc: null
  value: 0.5
checkpoints_dir:
  desc: null
  value: ./checkpoints
continue_train:
  desc: null
  value: false
crop_size:
  desc: null
  value: 256
dataroot:
  desc: null
  value: /home/guest1/ellen_data/UKB_quality_data2_combined/input_20220623_512_n1000
dataset_mode:
  desc: null
  value: unaligned
direction:
  desc: null
  value: AtoB
display_env:
  desc: null
  value: main
display_freq:
  desc: null
  value: 400
display_id:
  desc: null
  value: 1
display_ncols:
  desc: null
  value: 4
display_port:
  desc: null
  value: 8097
display_server:
  desc: null
  value: http://localhost
display_winsize:
  desc: null
  value: 256
epoch:
  desc: null
  value: latest
epoch_count:
  desc: null
  value: 1
gan_mode:
  desc: null
  value: lsgan
gpu_ids:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
init_gain:
  desc: null
  value: 0.02
init_type:
  desc: null
  value: normal
input_nc:
  desc: null
  value: 3
isTrain:
  desc: null
  value: true
lambda_A:
  desc: null
  value: 10.0
lambda_B:
  desc: null
  value: 10.0
lambda_identity:
  desc: null
  value: 0.5
load_iter:
  desc: null
  value: 0
load_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.0002
lr_decay_iters:
  desc: null
  value: 50
lr_policy:
  desc: null
  value: linear
max_dataset_size:
  desc: null
  value: .inf
model:
  desc: null
  value: cycle_gan
n_epochs:
  desc: null
  value: 100
n_epochs_decay:
  desc: null
  value: 300
n_layers_D:
  desc: null
  value: 3
name:
  desc: null
  value: ellen_dwt_uresnet2_3_512n1000_TEST
ndf:
  desc: null
  value: 64
netD:
  desc: null
  value: basic
netG:
  desc: null
  value: ellen_dwt_uresnet2_3
ngf:
  desc: null
  value: 16
no_dropout:
  desc: null
  value: true
no_flip:
  desc: null
  value: true
no_html:
  desc: null
  value: false
norm:
  desc: null
  value: instance
num_threads:
  desc: null
  value: 2
output_nc:
  desc: null
  value: 3
patience:
  desc: null
  value: 10
phase:
  desc: null
  value: train
pool_size:
  desc: null
  value: 50
preprocess:
  desc: null
  value: resize_and_crop
print_freq:
  desc: null
  value: 100
save_by_iter:
  desc: null
  value: false
save_epoch_freq:
  desc: null
  value: 5
save_latest_freq:
  desc: null
  value: 5000
serial_batches:
  desc: null
  value: false
suffix:
  desc: null
  value: ''
update_html_freq:
  desc: null
  value: 1000
use_wandb:
  desc: null
  value: true
verbose:
  desc: null
  value: false
